chore: fix lint issues
Signed-off-by: Emilien Escalle <emilien.escalle@escemi.com>

diff --git a/.github/workflows/__tests-docker.yml b/.github/workflows/__tests-docker.yml
--- a/.github/workflows/__tests-docker.yml
+++ b/.github/workflows/__tests-docker.yml
@@ -3,16 +3,18 @@ name: Shared - Tests - Docker
 on:
   workflow_call:
 
+permissions: {}
+
 jobs:
   build-images:
-    # FIXME: This is a workaround for having workflow actions. See https://github.com/orgs/community/discussions/38659
+    uses: hoverkraft-tech/ci-github-container/.github/workflows/docker-build-images.yml@00be6bf5e8054d319e621cd8523cc05ca5102462 # 0.25.0
     permissions:
-      id-token: write
       contents: read
       packages: write
       issues: read
       pull-requests: read
-    uses: hoverkraft-tech/ci-github-container/.github/workflows/docker-build-images.yml@00be6bf5e8054d319e621cd8523cc05ca5102462 # 0.25.0
+      # FIXME: This is a workaround for having workflow actions. See https://github.com/orgs/community/discussions/38659
+      id-token: write
     with:
       oci-registry: ${{ vars.OCI_REGISTRY }}
       images: |
@@ -42,6 +44,9 @@ jobs:
 
   tests-docker:
     name: Tests - Docker
+    permissions:
+      contents: read
+      packages: read
     runs-on: ubuntu-latest
     needs: build-images
     env:
@@ -70,7 +75,7 @@ jobs:
           if $DOCKER_COMPOSE_EXEC 'dpkg -l | grep -q "ucaresystem-core"'; then
             echo 'APT packages installed: pass' && exit 0
           else
-            echo 'APT packages installed: fail' && exit 1
+            echo '::error ::APT packages installed: fail' && exit 1
           fi
 
       - name: Validate Ansible changes in host - SSH keys
@@ -78,7 +83,7 @@ jobs:
           if $DOCKER_COMPOSE_EXEC 'test -f ~/.ssh/id_rsa_escemi'; then
             echo 'SSH keys installed: pass' && exit 0
           else
-            echo 'SSH keys installed: fail' && exit 1
+            echo '::error ::SSH keys installed: fail' && exit 1
           fi
 
       - name: Validate Ansible changes in host - GPG keys
@@ -86,7 +91,7 @@ jobs:
           if $DOCKER_COMPOSE_EXEC 'gpg --list-keys | grep -q "/home/ubuntu/.gnupg/pubring.kbx"' ; then
             echo 'GPG keys installed: pass' && exit 0
           else
-            echo 'GPG keys installed: fail' && exit 1
+            echo '::error ::GPG keys installed: fail' && exit 1
           fi
 
       - name: Validate Ansible changes in host - docker
@@ -94,13 +99,13 @@ jobs:
           if $DOCKER_COMPOSE_EXEC 'docker --version | grep -q "Docker"'; then
             echo 'Docker installed: pass' && exit 0
           else
-            echo 'Docker installed: fail' && exit 1
+            echo '::error ::Docker installed: fail' && exit 1
           fi
 
           if $DOCKER_COMPOSE_EXEC 'docker-compose --version | grep -q "Docker Compose"'; then
-            echo 'Docker installed: pass' && exit 0
+            echo 'Docker compose installed: pass' && exit 0
           else
-            echo 'Docker installed: fail' && exit 1
+            echo '::error ::Docker compose installed: fail' && exit 1
           fi
 
       - name: Validate Ansible changes in host - zsh
@@ -108,7 +113,7 @@ jobs:
           if $DOCKER_COMPOSE_EXEC 'zsh --version | grep -q "zsh"'; then
             echo 'Zsh installed: pass' && exit 0
           else
-            echo 'Zsh installed: fail' && exit 1
+            echo '::error ::Zsh installed: fail' && exit 1
           fi
 
       - name: Validate Ansible changes in host - nodejs & nvm & Yarn
@@ -116,19 +121,19 @@ jobs:
           if $DOCKER_COMPOSE_EXEC 'node --version | grep -Eq "^v[0-9.]+$"'; then
             echo 'Nodejs installed: pass' && exit 0
           else
-            echo 'Nodejs installed: fail' && exit 1
+            echo '::error ::Nodejs installed: fail' && exit 1
           fi
 
           if $DOCKER_COMPOSE_EXEC 'nvm --version | grep -Eq "^[0-9.]+$"'; then
             echo 'Nvm installed: pass' && exit 0
           else
-            echo 'Nvm installed: fail' && exit 1
+            echo '::error ::Nvm installed: fail' && exit 1
           fi
 
           if $DOCKER_COMPOSE_EXEC 'yarn --version | grep -Eq "^[0-9.]+$"'; then
             echo 'Yarn installed: pass' && exit 0
           else
-            echo 'Yarn installed: fail' && exit 1
+            echo '::error ::Yarn installed: fail' && exit 1
           fi
 
       - name: Validate Ansible changes in host - PHP & Composer
@@ -136,11 +141,11 @@ jobs:
           if $DOCKER_COMPOSE_EXEC 'php --version | grep -q "PHP"'; then
             echo 'PHP installed: pass' && exit 0
           else
-            echo 'PHP installed: fail' && exit 1
+            echo '::error ::PHP installed: fail' && exit 1
           fi
 
           if $DOCKER_COMPOSE_EXEC 'composer --version | grep -q "Composer"'; then
             echo 'Composer installed: pass' && exit 0
           else
-            echo 'Composer installed: fail' && exit 1
+            echo '::error ::Composer installed: fail' && exit 1
           fi
