fix: install playbooks
Signed-off-by: Emilien Escalle <emilien.escalle@escemi.com>

diff --git a/.github/workflows/__tests-vm.yml b/.github/workflows/__tests-vm.yml
--- a/.github/workflows/__tests-vm.yml
+++ b/.github/workflows/__tests-vm.yml
@@ -21,17 +21,29 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
 
-      - name: Set up QEMU VM
-        id: setup-qemu-vm
-        uses: ./.github/actions/setup-qemu-vm
+      - name: Set up QEMU and KVM
+        uses: ./.github/actions/setup-qemu-kvm
+
+      - name: Build VM image to boot
+        id: build-qcow-image
+        uses: ./.github/actions/build-qcow-image
         with:
-          iso-url: https://releases.ubuntu.com/24.04.2/ubuntu-24.04.2-desktop-amd64.iso
+          iso-url: https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img
+          user: ubuntu
+          password: ubuntu-pass
+
+      - name: Boot QEMU VM
+        id: boot-qemu-vm
+        uses: ./.github/actions/boot-qemu-vm
+        with:
+          image-name: ${{ steps.build-qcow-image.outputs.image-name }}
+          user: ubuntu
 
       - name: Run install script
         run: |
           ssh-keyscan -p 2222 -H 127.0.0.1 >> ~/.ssh/known_hosts
-          ${{ steps.setup-qemu-vm.outputs.ssh-command }} "wget -qO- \"$INSTALL_SCRIPT\" | sudo bash && sudo touch /e2e.success"
+          ${{ steps.boot-qemu-vm.outputs.ssh-command }} "wget -qO- \"$INSTALL_SCRIPT\" | sudo bash && sudo touch /e2e.success"
 
       - name: Validate Ansible changes in host - Snap packages
         run: |
-          ${{ steps.setup-qemu-vm.outputs.ssh-command }} '[ -f /e2e.success ] && echo "✅ Success" || { echo "❌ Setup failed"; exit 1; }'
+          ${{ steps.boot-qemu-vm.outputs.ssh-command }} '[ -f /e2e.success ] && echo "✅ Success" || { echo "❌ Setup failed"; exit 1; }'
